# Generated by Django 4.2.5 on 2023-10-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_alter_productimage_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstock',
            old_name='price',
            new_name='actual_price',
        ),
    ]
