# Generated by Django 4.2.5 on 2023-12-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, to='product_management.attribute'),
        ),
    ]
