# Generated by Django 4.0.7 on 2023-12-18 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product_management.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_management', '0008_alter_productclass_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.FileField(upload_to=product_management.models.review_directory_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
