# Generated by Django 4.0.7 on 2023-12-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0009_productreviewimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReviewImages',
        ),
    ]
