# Generated by Django 4.0.7 on 2023-12-18 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_management', '0011_productreviewimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReviewImages',
            new_name='ProductReviewImage',
        ),
    ]
