# Generated by Django 4.2.5 on 2023-11-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment Completed', 'PaymentCompleted'), ('Payment Cancelled', 'PaymentCancelled'), ('Payment Failed', 'PaymentFailed'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Declined', 'Declined'), ('Awaiting Shipment', 'AwaitingShipment'), ('Awaiting Pickup', 'AwaitingPickup'), ('Compeleted', 'Compeleted')], max_length=100),
        ),
    ]
