# Generated by Django 4.2.5 on 2023-11-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_order_payment_info_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment Completed', 'PaymentCompleted'), ('Payment Cancelled', 'PaymentCancelled'), ('Payment Failed', 'PaymentFailed'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Declined', 'Declined'), ('Awaiting Shipment', 'AwaitingShipment'), ('Awaiting Pickup', 'AwaitingPickup'), ('Compeleted', 'Compeleted')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.order')),
            ],
        ),
    ]
