# Generated by Django 4.2.5 on 2023-11-08 19:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_management', '0005_alter_product_price_alter_productstock_actual_price_and_more'),
        ('card_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CardUnit',
            new_name='CartUnit',
        ),
        migrations.RenameField(
            model_name='cartunit',
            old_name='card',
            new_name='cart',
        ),
    ]
